name: Build Android APK with Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Run Buildozer Action
      uses: ArtemisAnatol/buildozer-action@v1
      with:
        workdir: .
        buildozer_version: master

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: EvolutionControl-Android-APK
        path: bin/*.apk
