name: Build Android APK with Official Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch: # عشان تشغله بإيدك من الموبايل في أي وقت

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    # استخدام الأكشن الرسمي والمدعوم من Kivy مباشرة
    - name: Buildozer Action
      uses: kivy/buildozer-action@master
      with:
        workdir: .
        buildozer_version: stable

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: EvolutionControl-Android-APK
        path: bin/*.apk
